- name: Tear down existing services
  community.docker.docker_compose:
    project_src: /test-github-buildx-push/
    state: absent
- name: Copy docker-compose to remote server
  ansible.builtin.copy:
    src: ../docker-compose.yml
    dest: /test-github-buildx-push/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
- name: Run docker-compose
  community.docker.docker_compose:
    project_src: /test-github-buildx-push/
    build: false
    state: present
    pull: true
    remove_orphans: true
