---
- name: updateansible
  hosts: all
  become: true
  tasks:
    - name: stop docker compose
      shell:
        cmd: "docker compose down"
    - name: artifact
      id: artifact1
      type: github
      host: https://github.com
      project: test-github-buildx-push/ansible
      branch: main
      file: docker-compose.yml
      dest: git@github.com:Murawev/test-github-buildx-push.git
      validate_certs: false
    - name: Run docker-compose
      community.docker.docker_compose:
        project_src: /test-github-buildx-push/
        build: false
        register: output
