name: upload artifact

on:
  push:
    branches:
      - 'main'

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          path: /test-github-buildx-push/artifacts
          name: artifact-docker
