name: upload artifact

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: docker-compose/docker-compose.yml
      - name: Run ansible playbook
        run: |
          cd test-github-buildx-push/ansible
          ansible-playbook -i inventory updatestage.yml


          













