name: upload artifact

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositort
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: ./artifacts
          overwrite: true

          













