name: Build Go binary & OCI image & push to CR & update remote server

on:
  push:
    branches:
      - 'main'

jobs:
  build_oci_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/murawev/test-github-buildx-push:latest

  update_remote:
    runs-on: ubuntu-latest
    needs: build_oci_push
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install ansible dependencies
        run: |
          python --version
          pipx inject ansible-core requests docker
      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: updatestage.yml
          directory: ./ansible
          key: ${{secrets.SSH_KEY}}
          options: |
            --inventory ./inventory.ini
